services:
  dash-app:
    build: .
    ports:
      - "8050:8050"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./MTA_Ridership_by_DATA_NY_GOV.csv:/app/MTA_Ridership_by_DATA_NY_GOV.csv
      - .:/app
    restart: always