name: CI for Dash App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add your tests here (if any), or just check the app works
        curl http://localhost:8050

    - name: Build Docker image
      run: |
        docker build -t dash-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8050:8050 dash-app

    - name: Check app is running
      run: |
        curl http://localhost:8050